import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import Navbar from '@/components/Navbar/Navbar';
import { Toaster } from "react-hot-toast";
import './globals.css';

// const geistSans = GeistSans();
// const geistMono = GeistMono();

export const metadata = {
  title: 'GDSC NIT Calicut',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <div className="max-w-[110rem] mx-auto">
          <Navbar />
          <Toaster
            position="bottom-right"
            reverseOrder={false}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
